# Generated by Django 4.0 on 2022-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
