# Generated by Django 4.0 on 2022-04-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bahan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
