# Generated by Django 4.0 on 2022-04-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_bahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bahan',
        ),
    ]
