# Generated by Django 4.0 on 2022-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
