# Generated by Django 4.0 on 2022-04-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_product_bahan'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Pesanan_History',
            fields=[
                ('id_detail_pesanan', models.IntegerField(default='', primary_key=True, serialize=False, unique=True)),
                ('lokasi_pengiriman', models.CharField(max_length=225, null=True)),
                ('kode_unik', models.IntegerField()),
                ('metode_bayar', models.CharField(max_length=10, null=True)),
                ('metode_pesanan', models.CharField(max_length=15, null=True)),
                ('is_carted', models.IntegerField(default='0')),
                ('is_processed', models.IntegerField(default='0')),
                ('status_bayar', models.CharField(default='Belum bayar', max_length=20)),
                ('biaya_ongkir', models.IntegerField(default='0')),
                ('date_detail_pesanan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_detail_pesanan',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nama_depan', models.TextField(blank=True, max_length=20)),
                ('nama_belakang', models.TextField(blank=True, max_length=20)),
                ('jenis_kelamin', models.TextField(blank=True, max_length=15)),
                ('hp', models.CharField(blank=True, max_length=13, null=True)),
                ('alamat', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpen', models.CharField(default='1', max_length=5)),
                ('user_id', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('isOpen',),
            },
        ),
        migrations.CreateModel(
            name='Pesanan_History',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False, unique=True)),
                ('quantity_history', models.CharField(max_length=10)),
                ('is_activate', models.IntegerField(default='0')),
                ('date_added_history', models.DateTimeField(auto_now_add=True)),
                ('detail_id_pesanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usr.detail_pesanan_history')),
                ('product_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesananHistory', to='product.product')),
                ('user_id_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usr.profile')),
            ],
            options={
                'ordering': ('-date_added_history',),
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesanans', to='product.product')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
