# Generated by Django 4.0 on 2022-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_pesanan_history',
            name='is_carted',
        ),
        migrations.RemoveField(
            model_name='pesanan_history',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='detail_pesanan_history',
            name='is_checkout',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='pesanan_history',
            name='is_checkout',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='pesanan_history',
            name='is_history',
            field=models.IntegerField(default='0'),
        ),
    ]
