# Generated by Django 4.0 on 2022-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_remove_detail_pesanan_history_is_carted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hp',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
