# Generated by Django 4.0 on 2022-05-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0005_alter_pesanan_history_quantity_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan_history',
            name='is_history',
        ),
        migrations.AddField(
            model_name='detail_pesanan_history',
            name='is_delivered',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='detail_pesanan_history',
            name='is_ready',
            field=models.IntegerField(default='0'),
        ),
    ]
