# Generated by Django 4.0 on 2022-05-07 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0007_pesanan_history_is_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pesanan_history',
            name='date_detail_pesanan',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 2, 59, 42, 577469, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 2, 59, 42, 574746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesanan_history',
            name='date_added_history',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 2, 59, 42, 575873, tzinfo=utc)),
        ),
    ]
