# Generated by Django 4.0 on 2022-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0010_pesanan_history_is_stokupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan_history',
            name='is_review',
            field=models.IntegerField(default='0'),
        ),
    ]
