# Generated by Django 4.0 on 2022-05-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0011_pesanan_history_is_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan_history',
            name='is_review',
        ),
    ]
