# Generated by Django 4.0 on 2022-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0013_remove_storestatus_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='note_customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='toping_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pesanan_history',
            name='note_customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesanan_history',
            name='toping_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
