# Generated by Django 4.0 on 2022-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0015_alter_pesanan_toping_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='price_toping',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pesanan_history',
            name='price_toping',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
