from django.urls import include, path
from usr import views

urlpatterns = [
    path('usrs/<slug:user_ids>/', views.GetUser.as_view()),
    path('usr/store-status', views.GetStoreStatus.as_view()),
    path('usr/store-status-update/', views.update_status_restauran),
    path('usr/login/', views.TokenUserView.as_view()),
    path('usr/admin-login/', views.TokenAdminView.as_view()),
    path('usr/cart-store/', views.post_cart),
    path('usr/cart-delete/<int:pk>', views.delete_cart),
    path('usr/product-delete/<int:pk>', views.delete_product),
    path('usr/cart-update/<slug:cart_ids>/', views.update_cart),
    path('usr/cart-history-store/', views.post_cartHistory),
    path('usr/cart-update-history/<slug:cart_ids>/', views.update_cart_history),
    path('usr/update-history-cart/<slug:user_ids>/', views.CartHistory.as_view()),
    path('usr/update-history-cart', views.CartHistoryAdmin.as_view()),
    path('usr/update-product-stok', views.UpdateProductStok.as_view()),
    path('usr/detail-history-store/', views.post_detailHistory),
    path('usr/cart-lists/<slug:user_ids>/', views.CartLists.as_view()),
    path('usr/cart-lists-id', views.HistoryCartListsId.as_view()),
    path('products/all', views.AllProductsList.as_view()),
    path('products/most-ordered', views.MostOrderedProduct.as_view()),
    path('usr/history-cart-lists/<slug:user_ids>/', views.HistoryCartLists.as_view()),
    path('usr/delete-cart-bulk/', views.DeleteCartBulk.as_view()),
    path('usr/detail-checkout-cart-lists/<slug:fk>/', views.DetailCheckOutCartLists.as_view()),
    path('usr/transaksi-user-pickup-lists/', views.PickUpListsAdmin.as_view()),
    path('usr/transaksi-user-delivery-lists/', views.DeliveryListsAdmin.as_view()),
    path('usr/riwayat-user-cart-lists/', views.RiwayatCartListsAdmin.as_view()),
    path('usr/find-riwayat-user-cart-lists', views.RiwayatCartListsAdmin.as_view()),
    path('usr/find-statistik-user-cart-lists', views.StatistikAllUserOrderLists.as_view()),
    path('usr/history-user-cart-lists/', views.HistoryCartListsAdmin.as_view()), 
    path('usr/all-user-order-lists', views.StatistikAllUserOrderLists.as_view()), 
    path('usr/apriori-data', views.AprioriData.as_view()), 
    path('usr/history-done-user-cart-lists/<slug:user_ids>', views.HistoryCartListsDone.as_view()),
    path('usr/riwayat-done-user-cart-lists/<slug:user_ids>', views.RiwayatCartListsDone.as_view()),
    path('usr/history-user-cart-lists/<slug:fk>', views.HistoryCartListsAdminById.as_view()),
    path('usr/update-status-bayar/<slug:fk>', views.update_status_bayar),
    path('usr/update-status-pesanan/<slug:fk>', views.update_status_pesanan),
    path('usr/update-status-kirim/<slug:fk>', views.update_status_kirim),
    path('usr/update-status-stok/<slug:fk>', views.update_status_stok),
    # path('usr/product-update-stok', views.UpdateProductStok.as_view()),
    path('usr/product-update-stok/<slug:fk>', views.update_stok),
    path('usr/update/<slug:userId>/', views.update_user_detail),
    path('usr/post-detail/', views.UserDetailCreate.as_view()),
]
